### PR TITLE
fix(action cable): check ping time and singal a connection lost if it…

### LINKED ISSUE #4: handle connection lost event
is there a way we can detect connection being lost?
will it call the disconnect event on a channel or should the cable has an event like the following:
```dart
cable = ActionCable.Connect(
      'ws://example.com/cable',
      onConnected: () {},
      onConnectionLost: (){}
    );
``` 
any thoughts?

### PR DESCRIPTION
**Pull request by Dreamersoul**
… is more than 6 seconds

fix #4

I have followed the following documentation [anycable  documentation](https://docs.anycable.io/v06/#/misc/action_cable_protocol?id=ping)

### CODE REVIEW

**Comment by namiwang** [comment]
@Dreamersoul 

Hi! Thanks for the PR, sorry for the delay, missed the notification, my bad.

LGTM except for internal vars being public without a _, could you help with that, please?

**Comment by Dreamersoul** [comment]
Sure will update the PR tonight and let you know!

**Comment by Dreamersoul** [comment]
done 👍

**Comment by namiwang** [comment]
@all-contributors please add @Dreamersoul for code

**Pull request merged**
