### PR TITLE
Null-Safety

### PR DESCRIPTION
**Pull request by fareesh**

### CODE REVIEW

**Comment by fareesh** [comment]
Fixes #11

**Comment by Buk1m** [comment]
Null-safety  support would be awesome. @namiwang Is there anything stopping this PR from merging?

**Comment by namiwang** [comment]
Hi, thanks for the PR!

I'm not currently working with dart and flutter, so I haven't touched on this project in a while, sorry for the delay.

I'm gonna merge this assuming it has been tested.

**Comment by namiwang** [comment]
@all-contributors please add @fareesh  for code

**Pull request merged**
